sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t namskygreen/react-app -f Dockerfile.dev .

#  -- --coverage : test를 자세하게 보여줌
# -e CI=true : travis가 작동하기 위한 추가 부분
script:
  - docker run -e CI=true namskygreen/react-app npm run test -- --coverage

# after_success:
#   - echo "Test done"

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: DockerReactApp-env
  # S3 는 elasticbeanstalk을 생성하면 자동으로 생성한다.
  bucket_name: elasticbeanstalk-ap-northeast-2-972153559337
  bucket_path: docker-react-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
